source 'https://github.com/slb2709673/HLTest.git'

use_frameworks!

platform :ios, '9.0'

target 'HLCommon_Example' do
  pod 'HLCommon', :path => '../'
	
  target 'HLCommon_Tests' do
    inherit! :search_paths

    
  end
end
